# Generated by Django 5.0.3 on 2024-03-29 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langCorrect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='native_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='native_language', to='langCorrect.languages'),
        ),
    ]
