# Generated by Django 5.0.3 on 2024-03-29 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langCorrect', '0002_alter_customuser_native_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='langCorrect.languages'),
        ),
    ]
