# Generated by Django 5.0.3 on 2024-03-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langCorrect', '0004_rename_languages_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(choices=[('A2', 'Новичок'), ('A1', 'Элементарный'), ('B2', 'Средний'), ('B1', 'Выше среднего'), ('C2', 'Продвинутый'), ('C1', 'Опытный')], default='Новичок', max_length=20),
        ),
    ]
