# Generated by Django 5.0.3 on 2024-03-30 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langCorrect', '0006_post_gender_post_native_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='level',
        ),
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A2', 'Новичок'), ('A1', 'Элементарный'), ('B2', 'Средний'), ('B1', 'Выше среднего'), ('C2', 'Продвинутый'), ('C1', 'Опытный')], default='Новичок', max_length=20)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='langCorrect.language')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
