# Generated by Django 5.0.3 on 2024-03-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langCorrect', '0009_remove_customuser_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='correctionsQuantity',
            field=models.IntegerField(default=0),
        ),
    ]
