# Generated by Django 5.0.3 on 2024-04-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langCorrect', '0011_sentence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correction',
            name='corrected',
        ),
        migrations.AddField(
            model_name='correction',
            name='commentary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='original',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
